export const salesData = [
    {
      name: 'Jan',
      "sales": 6500,
    },
    {
      name: 'Feb',
      "sales": 9000,
    },
    {
      name: 'Mar',
      "sales": 5500,
    },
    {
      name: 'May',
      "sales": 2780,
     },
    {
      name: 'Jun',
      "sales": 8890,
    },
    {
      name: 'Jul',
      "sales": 7390,         
    },
    {
      name: 'Agu',
      "sales": 9490,        
    },
    {
        name: 'Sep',
        "sales": 3490,      
    },
    {
        name: 'Oct',
        "sales": 6490,
    },
    {
        name: 'Nov',
        "sales": 3490,    
    },
    {
        name: 'Dec',
        "sales": 1490,
    },
  ];


  export const userRows = [
    { id: 1,
      username: 'jon Snow',
      avatar: "https://www.lensmen.ie/wp-content/uploads/2015/02/Profile-Portrait-Photographer-in-Dublin-Ireland..jpg",
      email: "jon@gmail.com",
      status: "active",
      transaction: "$120.00"
   },
    { id: 2,
     username: 'jon Snow', 
     avatar: "https://www.lensmen.ie/wp-content/uploads/2015/02/Profile-Portrait-Photographer-in-Dublin-Ireland..jpg", 
     email: "jon@gmail.com", 
     status: "active", 
     transaction: "$120.00" 
    },
    { id: 3, 
     username: 'jon Snow', 
     avatar: "https://www.lensmen.ie/wp-content/uploads/2015/02/Profile-Portrait-Photographer-in-Dublin-Ireland..jpg", 
     email: "hon@gmail.com", 
     status: "active", 
     transaction: "$120.00" 
    },
    { id: 4, 
      username: 'jon Snow', 
      avatar: "https://www.lensmen.ie/wp-content/uploads/2015/02/Profile-Portrait-Photographer-in-Dublin-Ireland..jpg", 
      email: "hon@gmail.com", 
      status: "active", 
      transaction: "$120.00" 
    },

    { id: 5, 
      username: 'jon Snow', 
      avatar: "https://www.lensmen.ie/wp-content/uploads/2015/02/Profile-Portrait-Photographer-in-Dublin-Ireland..jpg", 
      email: "hon@gmail.com", 
      status: "active", 
      transaction: "$120.00"
     },
    { id: 6, 
      username: 'jon Snow', 
      avatar: "https://www.lensmen.ie/wp-content/uploads/2015/02/Profile-Portrait-Photographer-in-Dublin-Ireland..jpg", 
      email: "hon@gmail.com", 
      status: "active", 
      transaction: "$120.00" 
    },
    { id: 7, 
      username: 'jon Snow', 
      avatar: "https://www.lensmen.ie/wp-content/uploads/2015/02/Profile-Portrait-Photographer-in-Dublin-Ireland..jpg", 
      email: "hon@gmail.com", 
      status: "active", 
      transaction: "$120.00" 
    },
    { id: 8, 
      username: 'jon Snow', 
      avatar: "https://www.lensmen.ie/wp-content/uploads/2015/02/Profile-Portrait-Photographer-in-Dublin-Ireland..jpg", 
      email: "hon@gmail.com", 
      status: "active", 
      transaction: "$120.00" 
    },
    { id: 9, 
      username: 'jon Snow', 
      avatar: "https://www.lensmen.ie/wp-content/uploads/2015/02/Profile-Portrait-Photographer-in-Dublin-Ireland..jpg", 
      email: "hon@gmail.com", 
      status: "active", 
      transaction: "$120.00" 
    },

];

export const productRows = [
  { id: 1,
    name: 'clothes',
    img: "https://mastermerchant.biz/wp-content/uploads/2015/11/multi-color-t-shirts.jpg ",
    stock: 123,
    status: "active",
    price: "$120.00"
 },
  { id: 2,
    name: 'clothes',
    img: "https://mastermerchant.biz/wp-content/uploads/2015/11/multi-color-t-shirts.jpg ",
    stock: 123,
    status: "active",
    price: "$120.00"
  },
  { id: 3, 
    name: 'clothes',
    img: "https://mastermerchant.biz/wp-content/uploads/2015/11/multi-color-t-shirts.jpg ",
    stock: 123,
    status: "active",
    price: "$120.00" 
  },
  { id: 4, 
    name: 'clothes',
    img: "https://mastermerchant.biz/wp-content/uploads/2015/11/multi-color-t-shirts.jpg ",
    stock: 123,
    status: "active",
    price: "$120.00" 
  },

  { id: 5, 
    name: 'clothes',
    img: "https://mastermerchant.biz/wp-content/uploads/2015/11/multi-color-t-shirts.jpg ",
    stock: 123,
    status: "active",
    price: "$120.00"
   },
  { id: 6, 
    name: 'clothes',
    img: "https://mastermerchant.biz/wp-content/uploads/2015/11/multi-color-t-shirts.jpg ",
    stock: 123,
    status: "active",
    price: "$120.00"
  },
  { id: 7, 
    name: 'clothes',
    img: "https://mastermerchant.biz/wp-content/uploads/2015/11/multi-color-t-shirts.jpg ",
    stock: 123,
    status: "active",
    price: "$120.00"
  },
  { id: 8, 
    name: 'clothes',
    img: "https://mastermerchant.biz/wp-content/uploads/2015/11/multi-color-t-shirts.jpg ",
    stock: 123,
    status: "active",
    price: "$120.00" 
  },
  { id: 9, 
    name: 'clothes',
    img: "https://mastermerchant.biz/wp-content/uploads/2015/11/multi-color-t-shirts.jpg ",
    stock: 123,
    status: "active",
    price: "$120.00" 
  },
  { id: 10, 
    name: 'clothes',
    img: "https://mastermerchant.biz/wp-content/uploads/2015/11/multi-color-t-shirts.jpg ",
    stock: 123,
    status: "active",
    price: "$120.00" 
  },
  { id: 11, 
    name: 'clothes',
    img: "https://mastermerchant.biz/wp-content/uploads/2015/11/multi-color-t-shirts.jpg ",
    stock: 123,
    status: "active",
    price: "$120.00" 
  },
  { id: 12, 
    name: 'clothes',
    img: "https://mastermerchant.biz/wp-content/uploads/2015/11/multi-color-t-shirts.jpg ",
    stock: 123,
    status: "active",
    price: "$120.00" 
  },
  { id: 13, 
    name: 'clothes',
    img: "https://mastermerchant.biz/wp-content/uploads/2015/11/multi-color-t-shirts.jpg ",
    stock: 123,
    status: "active",
    price: "$120.00" 
  },
  { id: 14, 
    name: 'clothes',
    img: "https://mastermerchant.biz/wp-content/uploads/2015/11/multi-color-t-shirts.jpg ",
    stock: 123,
    status: "active",
    price: "$120.00" 
  },

];

export const productData = [
  {
    name: 'Jan',
    "product": 2500,
  },
  {
    name: 'Feb',
    "product": 6000,
  },
  {
    name: 'Mar',
    "product": 4500,
  },
  {
    name: 'Apr',
    "product": 7500,
  },
  {
    name: 'May',
    "product": 3500,
  },
];

export const mailRows = [
  
  { id: 1,
    supervisor:'jon Snow',
    email:"I want to increase the stock quantity of the product...",
 },
  { id: 2,
    supervisor: 'jon Snow',
    email: "I want to increase the stock quantity of the product...",
},
{ id: 3,
  supervisor: 'jon Snow',
  email: "I want to decrease the stock quantity of the product ...",
},
{ id: 4,
  supervisor: 'jon Snow',
  email: "I want to increase the stock quantity of the product...",
},

{ id: 5,
  supervisor: 'jon Snow',
  email: "I want to decrease the stock quantity of the product ...",
},
{ id: 6,
  supervisor: 'jon Snow',
  email: "I want to increase the stock quantity of the product...",
},

];

export const reportRows = [
  
  { id: 1,
    supervisor:'jon Snow',
    email:"I want to increase the stock quantity of the product...",
    stock:"123",
    status:" Accepted",
 },
 { id: 2,
  supervisor:'jon Snow',
  email:"I want to increase the stock quantity of the product...",
  stock:"123",
  status:" Declined",
},
{ id: 3,
  supervisor:'jon Snow',
  email:"I want to increase the stock quantity of the product...",
  stock:"123",
  status:" Declined",
},
{ id: 4,
  supervisor:'jon Snow',
  email:"I want to increase the stock quantity of the product...",
  stock:"123",
  status:" Accepted",
},
{ id: 5,
  supervisor:'jon Snow',
  email:"I want to increase the stock quantity of the product...",
  stock:"123",
  status:" Accepted",
},
{ id: 6,
  supervisor:'jon Snow',
  email:"I want to increase the stock quantity of the product...",
  stock:"123",
  status:" Declined",
},
{ id: 7,
  supervisor:'jon Snow',
  email:"I want to increase the stock quantity of the product...",
  stock:"123",
  status:" Accepted",
},
{ id: 8,
  supervisor:'jon Snow',
  email:"I want to increase the stock quantity of the product...",
  stock:"123",
  status:" Declined",
},
{ id: 9,
  supervisor:'jon Snow',
  email:"I want to increase the stock quantity of the product...",
  stock:"123",
  status:" Declined",
},
{ id: 10,
  supervisor:'jon Snow',
  email:"I want to increase the stock quantity of the product...",
  stock:"123",
  status:" Accepted",
},
{ id: 11,
  supervisor:'jon Snow',
  email:"I want to increase the stock quantity of the product...",
  stock:"123",
  status:" Accepted",
},
];



export const warehouseRows = [
  { id: 1,
    name: 'wh1',
    location: "Ain shams",
    status: "active",
    mail:"eke",
 },
//  { id: 2,
//   name: 'wh2',
//   location: "Ain shams",
//   status: "in-active",
// },
// { id: 3,
//   name: 'wh3',
//   location: "Ain shams",
//   status: "active",
// },
// { id: 4,
//   name: 'wh4',
//   location: "Ain shams",
//   status: "in-active",
// },
// { id: 5,
//   name: 'wh5',
//   location: "Ain shams",
//   status: "active",
// },


];

export const requestsRows = [
  
  { id: 1,
    supervisor:'jon Snow',
    email:"I want to increase the stock quantity of the product...",
    stock:"123",
    status:" Accepted",
 },
 { id: 2,
  supervisor:'jon Snow',
  email:"I want to increase the stock quantity of the product...",
  stock:"123",
  status:" Declined",
},
{ id: 3,
  supervisor:'jon Snow',
  email:"I want to increase the stock quantity of the product...",
  stock:"123",
  status:" Declined",
},
{ id: 4,
  supervisor:'jon Snow',
  email:"I want to increase the stock quantity of the product...",
  stock:"123",
  status:" Accepted",
},
{ id: 5,
  supervisor:'jon Snow',
  email:"I want to increase the stock quantity of the product...",
  stock:"123",
  status:" Accepted",
},
];

export const supervisorRows = [
  { id: 1,
    name: 'clothes',
    img: "https://mastermerchant.biz/wp-content/uploads/2015/11/multi-color-t-shirts.jpg ",
    stock: 123,
    status: "active",
    price: "$120.00"
 },
  { id: 2,
    name: 'clothes',
    img: "https://mastermerchant.biz/wp-content/uploads/2015/11/multi-color-t-shirts.jpg ",
    stock: 123,
    status: "active",
    price: "$120.00"
  },
  { id: 3, 
    name: 'clothes',
    img: "https://mastermerchant.biz/wp-content/uploads/2015/11/multi-color-t-shirts.jpg ",
    stock: 123,
    status: "active",
    price: "$120.00" 
  },
  { id: 4, 
    name: 'clothes',
    img: "https://mastermerchant.biz/wp-content/uploads/2015/11/multi-color-t-shirts.jpg ",
    stock: 123,
    status: "active",
    price: "$120.00" 
  },

  { id: 5, 
    name: 'clothes',
    img: "https://mastermerchant.biz/wp-content/uploads/2015/11/multi-color-t-shirts.jpg ",
    stock: 123,
    status: "active",
    price: "$120.00"
   },


];